# Generated by Django 2.2.1 on 2019-05-26 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_cat', models.CharField(max_length=20, unique=True, verbose_name='asset category')),
                ('max_allowed', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=20, unique=True, verbose_name='department')),
            ],
            options={
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='stored', max_length=15, unique=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'status',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_loc', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_loc', models.CharField(max_length=20, unique=True, verbose_name='asset location')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Department')),
                ('zone_loc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='assets.Zone', verbose_name='zone')),
            ],
            options={
                'verbose_name_plural': 'locations',
                'ordering': ['asset_loc'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='asset name')),
                ('brand', models.CharField(blank=True, max_length=15)),
                ('model', models.CharField(blank=True, max_length=12, verbose_name='model number')),
                ('service_tag', models.CharField(blank=True, max_length=15, verbose_name='service tag')),
                ('ip_config', models.CharField(choices=[('DHCP', 'DHCP'), ('STATIC', 'STATIC'), ('N/A', 'N/A')], default='N/A', max_length=6, verbose_name='ip configuration')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('serial', models.CharField(blank=True, max_length=40, verbose_name='serial number')),
                ('os', models.CharField(blank=True, max_length=15, verbose_name='operating system')),
                ('ram', models.CharField(blank=True, max_length=12)),
                ('hd', models.CharField(blank=True, max_length=20, verbose_name='hard drive')),
                ('pro', models.CharField(blank=True, max_length=40, verbose_name='processor')),
                ('bios', models.CharField(blank=True, max_length=10, verbose_name='bios version')),
                ('firm', models.CharField(blank=True, max_length=20, verbose_name='firmware version')),
                ('ports', models.IntegerField(blank=True, default=None, null=True, verbose_name='number of ports')),
                ('ext', models.IntegerField(blank=True, default=None, null=True, verbose_name='phone extension')),
                ('p_date', models.DateField(blank=True, default=None, null=True, verbose_name='purchase date')),
                ('d_date', models.DateField(blank=True, default=None, null=True, verbose_name='deployment date')),
                ('i_date', models.DateField(blank=True, default=None, null=True, verbose_name='image date')),
                ('asset_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Category', verbose_name='asset category')),
                ('asset_loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Location', verbose_name='asset location')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Status', verbose_name='status')),
            ],
            options={
                'verbose_name_plural': 'pieces of equipment',
                'ordering': ['asset_cat', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date and time of incident')),
                ('incident', models.TextField(blank=True, null=True)),
                ('act', models.TextField(blank=True, choices=[('CHANGE', 'CHANGE'), ('SERVICE', 'SERVICE')], null=True, verbose_name='action taken')),
                ('act_detail', models.TextField(verbose_name='action detail')),
                ('result', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Equipment', verbose_name='asset name')),
            ],
            options={
                'verbose_name_plural': 'service calls',
                'ordering': ['-dt'],
            },
        ),
    ]
