# Generated by Django 2.2.1 on 2019-05-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_tag',
            field=models.CharField(blank=True, max_length=15, verbose_name='service tag'),
        ),
    ]
