# Generated by Django 2.2.1 on 2019-05-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True, verbose_name='purchase price'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='phone_num',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ext',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='phone extension'),
        ),
    ]
