# Generated by Django 2.2.1 on 2019-05-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190501_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='date and time of incident')),
                ('incident', models.TextField(blank=True, null=True)),
                ('act', models.TextField(blank=True, choices=[('CHANGE', 'CHANGE'), ('SERVICE', 'SERVICE')], null=True, verbose_name='action taken')),
                ('act_detail', models.TextField(verbose_name='action detail')),
                ('result', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Equipment', verbose_name='asset name')),
            ],
            options={
                'verbose_name_plural': 'service calls',
                'ordering': ['-dt'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AlterField(
            model_name='location',
            name='asset_loc',
            field=models.CharField(default='storage', max_length=20, unique=True, verbose_name='asset location'),
        ),
        migrations.AlterField(
            model_name='status',
            name='state',
            field=models.CharField(default='stored', max_length=15, unique=True, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
