# Generated by Django 2.2.1 on 2019-05-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190526_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='asset_loc',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='assets.Location', verbose_name='asset location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='assets.Status', verbose_name='status'),
        ),
    ]
